// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_GZIT4aRDAsWUnRx4aKIiSD6THTX0D3U',
    appId: '1:187969799744:web:a58ecd715e8616824a41a5',
    messagingSenderId: '187969799744',
    projectId: 'gymsagabackup',
    authDomain: 'gymsagabackup.firebaseapp.com',
    storageBucket: 'gymsagabackup.firebasestorage.app',
    measurementId: 'G-EVC4B253Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa2T6_ybltlZirZx-t7qGKr10xm25YpDM',
    appId: '1:187969799744:android:4476ceaf448808c94a41a5',
    messagingSenderId: '187969799744',
    projectId: 'gymsagabackup',
    storageBucket: 'gymsagabackup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJHhjeYmIBjvv5FDLlwgiaKDDtEHnt1Bw',
    appId: '1:187969799744:ios:608043de4cfd7e1a4a41a5',
    messagingSenderId: '187969799744',
    projectId: 'gymsagabackup',
    storageBucket: 'gymsagabackup.firebasestorage.app',
    androidClientId: '187969799744-qig28bk2bodc5b6c1l8n8dtni1dtvjka.apps.googleusercontent.com',
    iosClientId: '187969799744-tu7rnntaqp5o5pbfdisj6r04fctgfi11.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymsaga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJHhjeYmIBjvv5FDLlwgiaKDDtEHnt1Bw',
    appId: '1:187969799744:ios:608043de4cfd7e1a4a41a5',
    messagingSenderId: '187969799744',
    projectId: 'gymsagabackup',
    storageBucket: 'gymsagabackup.firebasestorage.app',
    androidClientId: '187969799744-qig28bk2bodc5b6c1l8n8dtni1dtvjka.apps.googleusercontent.com',
    iosClientId: '187969799744-tu7rnntaqp5o5pbfdisj6r04fctgfi11.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymsaga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_GZIT4aRDAsWUnRx4aKIiSD6THTX0D3U',
    appId: '1:187969799744:web:ded99331a41d0f2d4a41a5',
    messagingSenderId: '187969799744',
    projectId: 'gymsagabackup',
    authDomain: 'gymsagabackup.firebaseapp.com',
    storageBucket: 'gymsagabackup.firebasestorage.app',
    measurementId: 'G-R09HJPVFGQ',
  );

}
